services:
  - type: web
    name: BG BANK-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        value: postgresql://bgdave1:Eskeleme1@BG-BANK.render.com:5432/bgdave1
      - key: SECRET_KEY
        value: Eskeleme1@
